// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

// 分页request参数
type ListPagingRequest struct {
	Page     int    `json:"page,optional,default=1"`
	PageSize int    `json:"page_size,optional,default=10"`
	Gender   string `json:"gender,optional"`
}

type ExampleRequest struct {
	Name     string `valid:"stringlength(1|20),required" json:"name"`
	Email    string `valid:"email" json:"email"`
	Describe string `valid:"stringlength(0|200)" json:"describe,optional"`
}
