// Code generated by goctl. DO NOT EDIT.
package userhandler

import (
	"appBuilder/internal/service/resp"
	"net/http"

	"appBuilder/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	resp.SetErrorHandler()

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: GetCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: AuthLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/userInfo",
				Handler: CurrentAccountHandler(serverCtx),
			},
			// 退出登录
			{
				Method:  http.MethodGet,
				Path:    "/logout",
				Handler: AuthLogoutHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
	)
}
